In [79]:
import numpy as np

In [80]:
a = np.array([1,2,3])

In [81]:
print(a)

[1 2 3]


In [82]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [83]:
# geting dimension (ndim) called number dimension
a.ndim

1

In [84]:
b.ndim

2

In [85]:
#get shape

In [86]:
a.shape

(3,)

In [87]:
b.shape

(2, 3)

In [88]:
# Question-1
output = np.ones((5,5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9

print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful while copying array

In [89]:
a = np.array([1, 2, 3])
b = a
b[0] = -999
print("b-> ", b)
print("a-> ", a)
# actual array 'a' also changing while copying and modification

c = a.copy()
c[0] = -888
print("c-> ", c)
print("a-> ", a)


b->  [-999    2    3]
a->  [-999    2    3]
c->  [-888    2    3]
a->  [-999    2    3]


### Linear Algebra

In [90]:
# M(a*b) X N(b*c) => while matrix multiplication (no.of cols of M = no.of rows of N) 

a = np.ones((2, 3))
print("a = ", a);

b = np.full((3,2), 2)
print("b = ", b);

z = np.matmul(a, b);
print("z = ", z);

a =  [[1. 1. 1.]
 [1. 1. 1.]]
b =  [[2 2]
 [2 2]
 [2 2]]
z =  [[6. 6.]
 [6. 6.]]


In [91]:
# finding the determinant
# ---> determinant of identity matrix is 1
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics with NumPy

In [92]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
np.min(stats)

1

In [94]:
np.max(stats)

6

In [95]:
np.sum(stats)

21

In [96]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [97]:
before = np.array([[1,2,3],[4,5,6]])
print(before)

after = before.reshape((3,2))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [98]:
# vertical stack
v1 = np.array([1,2,3,4,5])
v2 = np.array([6,7,8,9,10])
np.vstack([v1,v2,v1,v2])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [99]:
# Horizontal stack
h1 = np.ones((2,4))
print(h1)
h2 = np.zeros((2,2))
print(h2)
np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Loading Data From Files

In [108]:
with open('data.txt') as f:
    lines = f.readlines()

# Remove line 3 (index 2 since it's 0-based)
lines.pop(2)

with open('cleaned_data.txt', 'w') as f:
    f.writelines(lines)

# Now load the cleaned file
data = np.genfromtxt('cleaned_data.txt', delimiter=',')
print(data)

[[  1.  13.  21.  45.  46. 100.  98.  45.  99.   0.  -1.   0.   3.   5.
    8.   9.   3.   2.   1.]
 [100.  99.  88.  20.  30.  45.   3.  47.   9.   0.  -1.   9.   2.   4.
   30.   7.   1.   3.   0.]]


In [117]:
filedata = np.genfromtxt('data.txt', delimiter=',', invalid_raise=False)
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  45  46 100  98  45  99   0  -1   0   3   5   8   9   3   2
    1]
 [100  99  88  20  30  45   3  47   9   0  -1   9   2   4  30   7   1   3
    0]]


C:\Users\hp\AppData\Local\Temp\ipykernel_25532\2859405203.py:1: ConversionWarning: Some errors were detected !
    Line #3 (got 21 columns instead of 19)
  filedata = np.genfromtxt('data.txt', delimiter=',', invalid_raise=False)


#### Boolean Masking and Advance Indexing


In [118]:
filedata > 50

array([[False, False, False, False, False,  True,  True, False,  True,
        False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False]])

In [119]:
filedata[filedata > 50]

array([100,  98,  99, 100,  99,  88])

In [122]:
#you can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[2,4,6]]

array([3, 5, 7])